additional package source for newer mesa-libGL
netbrain/zwift pull request #63
Opened 2024-01-17 20:59 UTC by fandan

Resolve glxinfo errors on recent Fedora host version (39) in combination with Radeon GPU

2024-01-17 21:08 UTC, netbrain commented on Dockerfile
> +RUN echo "deb http://ftp.de.debian.org/debian sid main" >> /etc/apt/sources.list
Maybe use the official mirror? 🤷

2024-01-18 13:44 UTC, netbrain requested changes

2024-01-18 13:44 UTC, netbrain commented on Dockerfile
> +RUN echo "deb http://ftp.de.debian.org/debian sid main" >> /etc/apt/sources.list
```suggestion
RUN echo "deb http://ftp.debian.org/debian sid main" >> /etc/apt/sources.list
```

2024-01-19 07:11 UTC, netbrain commented
Tested it locally, seems to work fine. Releasing it to the wild to see what happens.

2024-01-19 07:12 UTC, merged

2024-01-21 13:35 UTC, gaeljw commented
Worked fine for me, thanks folks!

(The issue described in comments of https://github.com/netbrain/zwift/issues/54 is solved :+1: )